apiVersion: v1
kind: Service
metadata: 
  name: mongodb-svc
  namespace: web-app
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb-svc
      protocol: TCP
      port: 27017
      targetPort: 27017