apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web-app
  labels:
    role: frontend
    env: test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: docknik19/webapp-frontend:1
        imagePullPolicy: Always
        env:
          name: REACT_APP_BACKEND_URL
          valueFrom:
           ConfigMapRef:
            name: app-config
            key: REACT_APP_BACKEND_URL
        port:
        - containerPort: 3000  
